spring.application.name=demo
server.servlet.context-path=/demo
# App
server.port=9090
spring.application.name=atpl-demo

# Actuator for K8s probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true